version: "3.7"
services:
  wireguard:
    image: robertfent1/wireguard-rpi-client
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    network_mode: host
    dns: 8.8.8.8
    restart: always
    container_name: wireguard-rpi-client
